title: Blog of Stupid
description: I'll try to share solutions to some of my problems here...

exclude:
  - node_modules
  - typescript
  - '*.tsbuildinfo'

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

github:
  private: true # used by pages-themes/primer
